### ISSUE TITLE
AAA Pattern

### ISSUE THREAD

**Issue by ilusi0n** [ColmBhandal/CsharpExtras#30]
**Requirement**

We should review all the unit tests to follow the [AAA Pattern](https://docs.microsoft.com/en-us/visualstudio/test/unit-test-basics?view=vs-2019).

**Value Proposition**

Using the pattern makes it easier to know what the test is actually testing.
```
//arrange
int value=0;
int expected=1;

//act
var result = plusOne(value);

//assert
Assert(expected,result)
```
**Design Ideas**

Following the AAA Pattern from Microsoft.

**Comment by hctrdev** [comment]
Thanks for the input! I haven't heard of this pattern before.
On this project we generally follow a *given, when, then* pattern. From your description I think the idea is pretty similar:

**Given:** The initial conditions for the test
**When:** The action that takes place in that initial state
**Then:** The output of that action (this is where we would assert the expected end-state vs the actual)

We use this pattern in the naming of the test methods, but generally do not put comments in the tests to split out the different sections. But I think we could start doing that to improve clarity.

What are your thoughts on that? Do you see other advantages of the AAA pattern over the one we currently use?

**Comment by ilusi0n** [comment]
Actually, the name of the tests should be as you are doing.
I don't think is wrong. Personally what I do is NameOfMethod_Given_Expecting but it's a matter of taste! 

The comments, using the AAA pattern, are just a complement for what you are doing at the moment with the tests names. One complements the other.
So yes, I think it would improve clarity for future contributors.
Is just a suggestion though!

**Comment by ColmBhandal** [comment]
Sounds good to me Hugo. Yes the two will complement each other. I approve.
