### ISSUE TITLE
Formalise Semantic Versioning & Release Strategy

### ISSUE THREAD

**Issue by ColmBhandal** [ColmBhandal/CsharpExtras#34]
Give a clear meaning to the semantic versions of releases: major minor, bugfix. Clearly specify what the consequences are for compatibility. Add this to a Wiki page. Also add a release strategy.

**Comment by hctrdev** [comment]
I always follow this spec for semantic versioning: https://semver.org/

What kind of information are you thinking of putting in the wiki? It is not worth re-writing the content that spec already defines.

**Comment by ColmBhandal** [comment]
Makes sense. We're going to have a high major version but that's OK I
suppose. Is there anywhere in the project Wiki or readme that explicitly
states we use semantic versioning? We should at least link to that doc.

**Comment by hctrdev** [comment]
I added a [wiki](https://github.com/ColmBhandal/CsharpExtras/wiki/Versioning) page with details around versioning. What do you think?
