### ISSUE TITLE
Figure out Our Next Release/Milestone

### ISSUE THREAD

**Issue by ColmBhandal** [ColmBhandal/CsharpExtras#38]
Our next release will be a breaking change, so we'll to update the major version. We should as many pending breaking changes as possible as part of this release. For this issue, we should decide what we're going to do for the next release & add a milestone for it. Consider adding some method e.g. a change log to track whether the repo is clean or dirty i.e. does it need a major release.

**Comment by hctrdev** [comment]
If we do decide to start keeping a changelog for this project, I found this spec pretty good: [keepachangelog](https://keepachangelog.com/en/1.0.0/). That is the one I use for my projects.

**Comment by ColmBhandal** [comment]
Agreed. Let's go with that format.
