### ISSUE TITLE
FirstIndexOf returns zero based index on one-based array

### ISSUE THREAD

**Issue by hctrdev** [ColmBhandal/CsharpExtras#58]
**Describe the bug**

Given a `IOneBasedArray<>` the method to find the first index of an item (`.FirstIndexOf(x)`) returns a zero based index instead of one-based.

**To Reproduce**

1. Create a new one-based array (e.g. of strings)
1. Add items to the array
1. Use the `FirstIndexOf` method to find the first index of an item that is included in the array

**Observed behavior**
The return value of the function will be zero-based. I.e. if the value is found at the first index of the array, it will return 0 instead of 1.

**Expected behavior**
Since the array is one-based, this function should return a one-based index that can be used in further operations.

**Comment by ColmBhandal** [comment]
Not a bug. `FirstIndexOf` belongs to Linq, which works on the array as an enumerable, which gives back 0-based indices always.
